from __future__ import annotations

import html
import json
import pathlib
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _esc(value: Any) -> str:
    return html.escape(str(value))


def _report_css() -> str:
    path = ROOT / "assets" / "report.css"
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def export_report(payload: dict[str, Any], fmt: str) -> str:
    if fmt == "json":
        return json.dumps(payload, indent=2, ensure_ascii=False, default=str)

    if fmt == "markdown":
        return _export_markdown(payload)

    if fmt == "html":
        return _export_html(payload)

    raise ValueError(f"Unsupported export format: {fmt}")


def _export_markdown(payload: dict[str, Any]) -> str:
    report = payload.get("report") or {}
    contract = payload.get("contract") or {}

    lines = [
        "# Data Contract Validation Report",
        "",
        f"- Generated at: {payload.get('generated_at', '-')}",
        f"- Contract: {contract.get('name', '-')}",
        f"- Score: {report.get('score', 0):.2%}",
        f"- Passed: {report.get('passed', 0)}",
        f"- Failed: {report.get('failed', 0)}",
        f"- Warnings: {report.get('warnings', 0)}",
        "",
        "## Results",
        "",
        "| Rule | Column | Type | Status | Violations | Message |",
        "|---|---:|---:|---:|---:|---|",
    ]

    for r in report.get("results", []):
        lines.append(
            "| {rule} | {col} | {typ} | {status} | {viol} | {msg} |".format(
                rule=r.get("rule_id", ""),
                col=r.get("column") or "-",
                typ=r.get("rule_type", ""),
                status=r.get("status", ""),
                viol=r.get("violations_count", 0),
                msg=str(r.get("message", "")).replace("|", "\\|"),
            )
        )

    return "\n".join(lines) + "\n"


def _export_html(payload: dict[str, Any]) -> str:
    report = payload.get("report") or {}
    contract = payload.get("contract") or {}
    css = _report_css()

    rows = []
    for r in report.get("results", []):
        status = r.get("status", "")
        severity_class = {
            "pass": "severity-info",
            "fail": "severity-critical",
            "warning": "severity-medium",
        }.get(status, "severity-low")

        badge_class = {
            "pass": "badge-info",
            "fail": "badge-critical",
            "warning": "badge-medium",
        }.get(status, "badge-low")

        rows.append(
            f"""
            <div class="finding {severity_class}">
              <div class="finding-header">
                <h3>{_esc(r.get('rule_id', ''))}</h3>
                <span class="badge {badge_class}">{_esc(status)}</span>
              </div>
              <p class="finding-narrative">{_esc(r.get('message', ''))}</p>
              <div class="finding-columns">
                <b>Column:</b> {_esc(r.get('column') or '-')}<br>
                <b>Type:</b> {_esc(r.get('rule_type', ''))}<br>
                <b>Violations:</b> {_esc(r.get('violations_count', 0))}
              </div>
            </div>
            """
        )

    return f"""<!doctype html>
<html lang="{_esc(payload.get('lang', 'en'))}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Data Contract Validation Report</title>
<style>{css}</style>
</head>
<body>
<div class="report-container">
  <header class="report-header">
    <div class="report-brand">
      <h1>Data Contract Validation Report</h1>
      <p>{_esc(contract.get('name', 'dataset'))}</p>
    </div>
    <dl class="report-meta">
      <div><dt>Generated</dt><dd>{_esc(payload.get('generated_at', '-'))}</dd></div>
      <div><dt>Score</dt><dd>{_esc(f"{report.get('score', 0):.2%}")}</dd></div>
      <div><dt>Passed</dt><dd>{_esc(report.get('passed', 0))}</dd></div>
      <div><dt>Failed</dt><dd>{_esc(report.get('failed', 0))}</dd></div>
      <div><dt>Warnings</dt><dd>{_esc(report.get('warnings', 0))}</dd></div>
    </dl>
  </header>
  <main class="report-section">
    {''.join(rows) or '<p>No results.</p>'}
  </main>
  <footer class="report-footer">
    Generated by Data Contract Studio.
  </footer>
</div>
</body>
</html>
"""